name: Flutter - Android & IOS Manual Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Specify branch'
        required: true
        default: 'master'
        type: choice
        options:
          - master
          - dev
          - merge-android-ios-github-workflow

jobs:
  build:
    runs-on: macos-latest  

    steps:
      - name: Checkout
        uses: actions/checkout@v4   
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'    

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install dependencies
        run: flutter pub get

      # IOS Related   
      - name: Install IOS dependencies
        run: |         
          cd ios
          pod install --repo-update
          cd ..  

      - name: Auto format dart code
        run: dart format .
        
      - name: Verify dart code is formatted
        run: dart format --output=none --set-exit-if-changed.

        # IOS Related   
      - name: Build IOS IPA
        run:  flutter build ios --release --no-codesign 
        # need apple developer account to build signed ipa   

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true
          working-directory: android

      - name: Create dev_config.json
        run: |
          mkdir -p config
          echo '${{ secrets.DEV_CONFIG_JSON }}' > config/dev_config.json

      - name: Deploy to Firebase App Distribution via Fastlane
        working-directory: android
        env:  
           FIREBASE_APP_ID: ${{secrets.ANDROID_APP_ID}}
           FIREBASE_CLI_TOKEN: ${{secrets.FIREBASE_CLI_TOKEN}}
        run: |  
          bundle exec fastlane deploy_to_firebase_distribution

