name: Flutter - IOS CI

on:
  push:
    branches:
      - integrate_ci_cd
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4     

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Install IOS dependencies
        run: |         
          cd ios
          pod install --repo-update
          cd ..

      - name: Auto format dart code
        run: dart format .
        
      - name: Verify dart code is formatted
        run: dart format --output=none --set-exit-if-changed .
      
      - name: Build IOS IPA
        run: flutter build ios --no-codesign

      - name: Upload ios build artifact to Firebase App Distribution
        uses: emertozd/Firebase-Distribution-Github-Action@v2
        with:
          appId: ${{secrets.IOS_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.GOOGLE_APP_CREDENTIALS}}
          groups: testers
          file: build/ios/iphoneos/Runner.app  


